services:
  frontend:
    depends_on:
      - backend

  backend:
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    volumes:
      - mongo:/data/db
    tmpfs:
      - /data/configdb

volumes:
  mongo:
