name: Deploy to Production

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  deploy_prod:
    name: Deploy to Production
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, ledge]
    env:
      TARGET_PATH: /srv/apps/ledge/prod
      HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      IMAGE_TAG: latest
    steps:
      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u antoine-navette --password-stdin

      - name: Retag images to latest
        run: |
          docker buildx imagetools create \
            ghcr.io/antoine-navette/ledge-backend:$HEAD_SHA \
            --tag ghcr.io/antoine-navette/ledge-backend:latest

          docker buildx imagetools create \
            ghcr.io/antoine-navette/ledge-frontend:$HEAD_SHA \
            --tag ghcr.io/antoine-navette/ledge-frontend:latest

      - name: Pull latest code
        run: |
          cd "$TARGET_PATH"
          git pull

      - name: Deploy
        run: |
          cd "$TARGET_PATH"
          docker compose pull
          docker compose run --rm --no-deps backend node dist/backend/scripts/migrate.js
          docker compose down --remove-orphans
          docker compose up -d
